BESTIARY = [
    {'name': 'Alien, Gray', 'type': 'Alien', 'specials': '', 'description': 'Waist tall, big eyes, and an slit mouth. Standard extraterestrial.',
        'hp': '5', 'toTarget': 'normal', 'av': '0', 'STR': '2', 'DEX': '4', 'INT': '6', 'PRE': '1', 'statBlock': '2/4/6/1'},
    {'name': 'Alien, Gray Boss', 'type': 'Alien', 'specials': 'Telepathy', 'description': 'Slightly smaller Gray, with bigger head. Has telepathy.',
        'hp': '10', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '5', 'INT': '6', 'PRE': '3', 'statBlock': '3/5/6/3'},
    {'name': 'Alien, Reptilian', 'type': 'Alien', 'specials': 'Contortionist', 'description': 'Clumsy, garrulous, strong. Alligator skin. Can squeeze through shockingly small openings.',
        'hp': '10', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '3', 'INT': '2', 'PRE': '1', 'statBlock': '6/3/2/1'},
    {'name': 'Alien, Reptilian (human form)', 'type': 'Alien', 'specials': 'Contortionist', 'description': 'Reptilians have a genetic splicer that can make them look human. Unstable: if badly injured or killed, will return to original form.',
     'hp': '4', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '3', 'INT': '2', 'PRE': '1', 'statBlock': '6/3/2/1'},
    {'name': 'Alien, Reptilian Officer', 'type': 'Alien', 'specials': 'Contortionist', 'description': 'A bigger, meaner Reptilian.',
        'hp': '15', 'toTarget': 'normal', 'av': '0', 'STR': '7', 'DEX': '3', 'INT': '4', 'PRE': '3', 'statBlock': '7/3/4/3'},
    {'name': 'Alien, Tall', 'type': 'Alien', 'specials': 'Leap', 'description': 'Taller and thinner than a human. Almond eyes. Sadistic. 5m vertical leap.',
        'hp': '7', 'toTarget': 'normal', 'av': '0', 'STR': '2', 'DEX': '4', 'INT': '6', 'PRE': '1', 'statBlock': '2/4/6/1'},
    {'name': 'Alien, Tall Supervisor', 'type': 'Alien', 'specials': 'Leap, Telepathy', 'description': 'Leader of a group of Talls. 5m vertical leap and Telepathy.',
        'hp': '12', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '5', 'INT': '6', 'PRE': '4', 'statBlock': '3/5/6/4'},
    {'name': 'Animal, Big Bear', 'type': 'Animal', 'specials': '', 'description': 'Grizzlies, polar bears, Kodiaks, and the like. Extremely aggressive. Difficult to scare off.',
        'hp': '17', 'toTarget': 'normal', 'av': '1', 'STR': '7', 'DEX': '4', 'INT': '0', 'PRE': '3', 'statBlock': '7/4/0/3'},
    {'name': 'Animal, Big Cat', 'type': 'Animal', 'specials': 'Stealthy', 'description': 'Lion, cougar, panther, etc.',
        'hp': '13', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '6/5/0/3'},
    {'name': 'Animal, Constrictor Snake', 'type': 'Animal', 'specials': 'Constrictor', 'description': 'Python, boa, etc.… A big one. On a successful strike, Danger Die 1 means grabbed, held, and crushed for 1d6+2 per turn. Opposed STR check to break free.',
        'hp': '12', 'toTarget': 'Easy', 'av': '0', 'STR': '5', 'DEX': '5', 'INT': '0', 'PRE': '2', 'statBlock': '5/5/0/2'},
    {'name': 'Animal, Dog', 'type': 'Animal', 'specials': 'Heightened Smell', 'description': 'Guard dogs, pet dogs, wild dogs, search dogs, police dogs, etc.',
        'hp': '3', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '3/5/0/3'},
    {'name': 'Animal, Large', 'type': 'Animal', 'specials': '', 'description': 'Moose, elk, black bear, boar, hyena, bull, etc. Adjust stats, if necessary, and give them the behavior of their species.',
        'hp': '8', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '0', 'PRE': '3', 'statBlock': '5/4/0/3'},
    {'name': 'Animal, Medium', 'type': 'Animal', 'specials': '', 'description': 'Baboon, badger, goat, jackal, deer, seal, octopus, etc.\nAdjust stats, if necessary, and give them the behavior of their species. Attacks cause 1d6-3 damage.',
        'hp': '3', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '3/5/0/3'},
    {'name': 'Animal, Mount', 'type': 'Animal', 'specials': '', 'description': 'Horse, camel, mule, etc. Can safely carry weight equivalent to two adults.',
        'hp': '7', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '4', 'INT': '0', 'PRE': '3', 'statBlock': '6/4/0/3'},
    {'name': 'Animal, Poisonous Snake', 'type': 'Animal', 'specials': 'Poisonous (Bite)', 'description': 'Cobra, rattler, cottonmouth, etc. Striking bite is a ranged attack. 1d6 poison damage per turn for 1-6 turns.',
     'hp': '2', 'toTarget': 'Hard', 'av': '0', 'STR': '1', 'DEX': '6', 'INT': '0', 'PRE': '2', 'statBlock': '1/6/0/2'},
    {'name': 'Animal, Raptor', 'type': 'Animal', 'specials': 'Distance Vision', 'description': 'Eagle, hawk, vulture, owl, etc.',
        'hp': '2', 'toTarget': 'Hard', 'av': '0', 'STR': '2', 'DEX': '6', 'INT': '0', 'PRE': '3', 'statBlock': '2/6/0/3'},
    {'name': 'Animal, Small', 'type': 'Animal', 'specials': '', 'description': 'Bat, rat, big spider, frog, toad, raven, lizard, scorpion, cat, weasel, monkey, rattlesnake, etc. Hard to hit, but easy to kill. Bite hurts but causes no damage, unless poisonous. Adjust stats, if necessary, and give them the behavior of their species.',
        'hp': '1', 'toTarget': 'Hard', 'av': '0', 'STR': '1', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '1/5/0/3'},
    {'name': 'Animal, Swarm', 'type': 'Animal', 'specials': '', 'description': 'Rats, insects, snakes, crows, fish, etc. They are all over you. They can attack every member of a party every turn.',
        'hp': '20', 'toTarget': 'Hard', 'av': '0', 'STR': '2', 'DEX': '6', 'INT': '0', 'PRE': '2', 'statBlock': '2/6/0/2'},
    {'name': 'Crocodile', 'type': 'Beast', 'specials': '', 'description': 'Biting power has STR 8. On successful strike, Danger Die 1 means bitten, held, and crushed for 2d6. Opposed STR check to break free.',
        'hp': '10', 'toTarget': 'Easy', 'av': '2', 'STR': '5', 'DEX': '4', 'INT': '0', 'PRE': '2', 'statBlock': '5/4/0/2'},
    {'name': 'Dire Wolf', 'type': 'Beast', 'specials': 'Heightened Smell', 'description': 'A huge wolf, five feet tall at the shoulder. Pack hunter, often found in groups of 1d6+2.',
        'hp': '12', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '6/5/0/3'},
    {'name': 'Elephant', 'type': 'Beast', 'specials': '', 'description': 'Prehensile trunk.', 'hp': '38',
        'toTarget': 'Easy', 'av': '1', 'STR': '8', 'DEX': '3', 'INT': '0', 'PRE': '2', 'statBlock': '8/3/0/2'},
    {'name': 'Giant Ant', 'type': 'Beast', 'specials': '', 'description': 'On successful attack with Danger Die showing 1 or 2: target grabbed, held, and lifted. Ant will try to carry away.',
        'hp': '20', 'toTarget': 'Easy', 'av': '', 'STR': '9', 'DEX': '3', 'INT': '0', 'PRE': '1', 'statBlock': '9/3/0/1'},
    {'name': 'Giant Ape', 'type': 'Beast', 'specials': 'Climber', 'description': 'Several stories tall. Excellent Climber',
        'hp': '79', 'toTarget': 'Easy', 'av': '0', 'STR': '8', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '8/5/0/3'},
    {'name': 'Giant Bat', 'type': 'Beast', 'specials': 'Echolocation', 'description': '5m wingspan. Bites.', 'hp': '11',
        'toTarget': 'Easy', 'av': '0', 'STR': '5', 'DEX': '6', 'INT': '0', 'PRE': '3', 'statBlock': '5/6/0/3'},
    {'name': 'Giant Boar', 'type': 'Beast', 'specials': 'Tusks', 'description': 'Really big, dangerous pig. 2m at shoulder.',
        'hp': '21', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '4', 'INT': '0', 'PRE': '2', 'statBlock': '6/4/0/2'},
    {'name': 'Giant Centipede', 'type': 'Beast', 'specials': 'Poisonous (Bite)', 'description': '6m long. Poisonous bite does 1-3 damage for 1-6 turns.',
     'hp': '2', 'toTarget': 'Hard', 'av': '1', 'STR': '2', 'DEX': '5', 'INT': '0', 'PRE': '1', 'statBlock': '2/5/0/1'},
    {'name': 'Giant Constrictor Snake', 'type': 'Beast', 'specials': 'Constrictor', 'description': 'Python, boa, etc.… 20m long. Can easily swallow a human. On a successful strike, Danger Die 1 means grabbed, held, and crushed for 2d6+2 per turn. Opposed STR check to break free. Might release during massive attack.',
        'hp': '30', 'toTarget': 'Easy', 'av': '0', 'STR': '7', 'DEX': '5', 'INT': '0', 'PRE': '2', 'statBlock': '7/5/0/2'},
    {'name': 'Giant Crab', 'type': 'Beast', 'specials': '', 'description': '2 attacks per turn. On successful attack with Danger Die showing 1 or 2: target grabbed, held, and lifted. ',
        'hp': '15', 'toTarget': 'normal', 'av': '3', 'STR': '6', 'DEX': '3', 'INT': '0', 'PRE': '2', 'statBlock': '6/3/0/2'},
    {'name': 'Giant Crocodile', 'type': 'Beast', 'specials': '', 'description': 'Biting power has STR 9. Bite does 2d6 damage. On successful strike, Danger Die 1 means bitten, held, and crushed for 3d6. Opposed STR check to break free.',
        'hp': '43', 'toTarget': 'Easy', 'av': '2', 'STR': '7', 'DEX': '3', 'INT': '0', 'PRE': '2', 'statBlock': '7/3/0/2'},
    {'name': 'Giant Eagle', 'type': 'Beast', 'specials': '', 'description': '3m wingspan. Crushing talons.', 'hp': '13',
        'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '6', 'INT': '0', 'PRE': '4', 'statBlock': '6/6/0/4'},
    {'name': 'Giant Fire Beetle', 'type': 'Beast', 'specials': 'Breath Weapon: Fire', 'description': '1m long. Very quick. Spit lava balls.',
        'hp': '2', 'toTarget': 'Hard', 'av': '2', 'STR': '3', 'DEX': '4', 'INT': '0', 'PRE': '1', 'statBlock': '3/4/0/1'},
    {'name': 'Giant Frog/Toad', 'type': 'Beast', 'specials': 'Sticky Tongue', 'description': '2m tall while sitting. 2m long tongue. Snapping bite attacks. On successful attack, Danger Die 1 means victim pulled into mouth with tongue. 1d6 dmg per turn.',
        'hp': '9', 'toTarget': 'Easy', 'av': '0', 'STR': '4', 'DEX': '5', 'INT': '0', 'PRE': '2', 'statBlock': '4/5/0/2'},
    {'name': 'Giant Lizard', 'type': 'Beast', 'specials': '', 'description': '4m long, without tail.', 'hp': '10',
        'toTarget': 'Easy', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '0', 'PRE': '2', 'statBlock': '5/4/0/2'},
    {'name': 'Giant Octopus', 'type': 'Beast', 'specials': '', 'description': '2 attacks per turn. If danger die shows 1, target is grabbed and must test STR to escape.',
        'hp': '26', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '6/5/0/3'},
    {'name': 'Giant Poisonous Snake', 'type': 'Beast', 'specials': 'Poisonous (Bite)', 'description': 'On successful attack with Danger Die showing 1 or 2: target poisoned 1d6 damage for 1-3 turns.',
     'hp': '6', 'toTarget': 'Easy', 'av': '0', 'STR': '4', 'DEX': '6', 'INT': '0', 'PRE': '2', 'statBlock': '4/6/0/2'},
    {'name': 'Giant Rat', 'type': 'Beast', 'specials': '', 'description': '1m tall at shoulder', 'hp': '4',
        'toTarget': 'Hard', 'av': '0', 'STR': '3', 'DEX': '5', 'INT': '0', 'PRE': '2', 'statBlock': '3/5/0/2'},
    {'name': 'Giant Scorpion', 'type': 'Beast', 'specials': 'Poisonous (Sting)', 'description': 'Claws and stinger. 5m long with the tail. On a successful attack, if the Danger Die shows 1 or 2, target has been stung by the tail. 1d6 poison damage per turn for 1d6 turns.',
     'hp': '26', 'toTarget': 'Easy', 'av': '1', 'STR': '5', 'DEX': '5', 'INT': '0', 'PRE': '2', 'statBlock': '5/5/0/2'},
    {'name': 'Giant Snake', 'type': 'Beast', 'specials': '', 'description': 'Danger Die 1 means victim swallowed. 1d6 dmg per turn.',
        'hp': '13', 'toTarget': 'Easy', 'av': '0', 'STR': '7', 'DEX': '5', 'INT': '0', 'PRE': '2', 'statBlock': '7/5/0/2'},
    {'name': 'Giant Spider', 'type': 'Beast', 'specials': 'Poisonous (Bite)', 'description': '2m tall at shoulder. Successful bite with danger die 1-3 means target paralyzed and suffering 1d6 damage for 1d6 rounds.',
     'hp': '13', 'toTarget': 'Easy', 'av': '0', 'STR': '5', 'DEX': '6', 'INT': '0', 'PRE': '2', 'statBlock': '5/6/0/2'},
    {'name': 'Giant Wasp', 'type': 'Beast', 'specials': 'Poisonous (Sting)', 'description': 'The size of a large dog. On hit, target suffers 1d6-2 damage for 1-3 rounds. Usually encountered in groups of 1d6+2.',
     'hp': '7', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '5', 'INT': '0', 'PRE': '2', 'statBlock': '4/5/0/2'},
    {'name': 'Gorilla', 'type': 'Beast', 'specials': 'Climber', 'description': 'Excellent climber, very strong',
        'hp': '10', 'toTarget': 'normal', 'av': '0', 'STR': '7', 'DEX': '5', 'INT': '0', 'PRE': '2', 'statBlock': '7/5/0/2'},
    {'name': 'Gorilla, Enhanced', 'type': 'Beast', 'specials': '', 'description': '', 'hp': '20',
        'toTarget': 'normal', 'av': '', 'STR': '6', 'DEX': '6', 'INT': '0', 'PRE': '3', 'statBlock': '6/6/0/3'},
    {'name': 'Killer Whale', 'type': 'Beast', 'specials': '', 'description': 'Bites for 1d6+2 damage.', 'hp': '45',
        'toTarget': 'Easy', 'av': '0', 'STR': '7', 'DEX': '4', 'INT': '0', 'PRE': '2', 'statBlock': '7/4/0/2'},
    {'name': 'Megolodon', 'type': 'Beast', 'specials': '', 'description': 'A really giant shark. Drawn to blood in the water up to a 1km away. Successful attack and Danger Die 1 means target is swallowed. All attacks do 2d6 damage.',
        'hp': '63', 'toTarget': 'Easy', 'av': '0', 'STR': '8', 'DEX': '4', 'INT': '0', 'PRE': '2', 'statBlock': '8/4/0/2'},
    {'name': 'Rhinoceros', 'type': 'Beast', 'specials': 'Charge Attack', 'description': 'Tramples and charges.',
        'hp': '23', 'toTarget': 'Easy', 'av': '2', 'STR': '7', 'DEX': '3', 'INT': '0', 'PRE': '3', 'statBlock': '7/3/0/3'},
    {'name': 'Shark', 'type': 'Beast', 'specials': '', 'description': 'Drawn to blood in water up to 1km away. Bite does 1d6+3 damage',
        'hp': '23', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '6/5/0/3'},
    {'name': 'Tiger', 'type': 'Beast', 'specials': 'Night Vision, Stealthy', 'description': 'Night vision, silent stalker, camouflage.',
        'hp': '19', 'toTarget': 'Easy', 'av': '0', 'STR': '7', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '7/5/0/3'},
    {'name': 'Warhorse', 'type': 'Beast', 'specials': '', 'description': 'Really tough horse.', 'hp': '10',
        'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '4', 'INT': '0', 'PRE': '3', 'statBlock': '6/4/0/3'},
    {'name': 'Wolf', 'type': 'Beast', 'specials': 'Heightened Smell', 'description': 'Pack hunter, usually found in groups of 1d6+1 wolves.',
        'hp': '6', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '4/5/0/3'},
    {'name': 'Brain Bot', 'type': 'Bot', 'specials': 'Heat Vision', 'description': 'Has instant access to all historical and scientific data. Capable of sophisticated communication and massive calculations. May have become self-aware. Probably controls a squadron of other bots, including security or soldier bots.',
        'hp': '10', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '10', 'PRE': '3', 'statBlock': '3/3/10/3'},
    {'name': 'Cargo Bot', 'type': 'Bot', 'specials': 'Heat Vision, Tractor Beam', 'description': 'Forklift on the front, tractor beam, and 2 massive pincer arms.',
        'hp': '20', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '3', 'INT': '0', 'PRE': '3', 'statBlock': '6/3/0/3'},
    {'name': 'House Bot', 'type': 'Bot', 'specials': 'Heat Vision', 'description': 'General cleaning and housework. Vacuum, mop. 1 low-output laser for spot removal. Able to cook a good meal with whatever it has.',
        'hp': '5', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '0', 'PRE': '3', 'statBlock': '3/3/0/3'},
    {'name': 'Medical Bot', 'type': 'Bot', 'specials': 'Heat Vision, Doctor', 'description': 'Can perform complex surgeries. When fully stocked, has enough onboard supply to hear 1d6 damage 20 times.',
        'hp': '5', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '3/5/0/3'},
    {'name': 'Repair Bot', 'type': 'Bot', 'specials': 'Heat Vision', 'description': 'Cutting torch, welding beam, 4 arms with grasping and multitool functions. Is able to answer engineering and how-to questions.',
        'hp': '15', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '3', 'INT': '0', 'PRE': '3', 'statBlock': '6/3/0/3'},
    {'name': 'Science Bot', 'type': 'Bot', 'specials': 'Heat Vision', 'description': 'Covered with sensors and measuring instruments. Is able to answer technical questions and give calculations.',
        'hp': '5', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '3/5/0/3'},
    {'name': 'Security Bot', 'type': 'Bot', 'specials': 'Heat Vision', 'description': 'Has a siren, two beam weapons, and one slug weapon. Is able to detain people with plasti-cuffs. 2 attacks per turn.',
        'hp': '30', 'toTarget': 'normal', 'av': '2', 'STR': '6', 'DEX': '6', 'INT': '0', 'PRE': '3', 'statBlock': '6/6/0/3'},
    {'name': 'Soldier Bot', 'type': 'Bot', 'specials': 'Heat Vision', 'description': '4 beam weapons. 4 attacks per turn. All attacks for 1d6+3 damage. Very agile. ',
        'hp': '35', 'toTarget': 'normal', 'av': '3', 'STR': '7', 'DEX': '6', 'INT': '0', 'PRE': '6', 'statBlock': '7/6/0/6'},
    {'name': 'Tank Bot', 'type': 'Bot', 'specials': 'Heat Vision', 'description': 'War machine. Covered with laser cannons. 3 attacks per turn. All attacks do 2d6+3 damage.',
        'hp': '75', 'toTarget': 'Easy', 'av': '4', 'STR': '10', 'DEX': '4', 'INT': '0', 'PRE': '3', 'statBlock': '10/4/0/3'},
    {'name': 'Worker Bot', 'type': 'Bot', 'specials': 'Heat Vision, Tractor Beam', 'description': 'General labor. Has a tractor beam and highly functional hands.',
        'hp': '15', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '3', 'INT': '0', 'PRE': '3', 'statBlock': '6/3/0/3'},
    {'name': 'Android', 'type': 'Construct', 'specials': '', 'description': 'A self-aware robot that looks human, is capabable of high-speed calculation and has instant access to massive amounts of information. May be motivated by obsucre non-human drives.',
        'hp': '15', 'toTarget': 'normal', 'av': '1', 'STR': '6', 'DEX': '6', 'INT': '6', 'PRE': '3', 'statBlock': '6/6/6/3'},
    {'name': 'Golem', 'type': 'Construct', 'specials': '', 'description': 'Magical statue come to life. Stone, iron, or clay. Danger die 1 means target is grabbed and held for 1d6 damage. Opposed STR check to break free.',
        'hp': '67', 'toTarget': 'Easy', 'av': '2', 'STR': '7', 'DEX': '3', 'INT': '0', 'PRE': '0', 'statBlock': '7/3/0/0'},
    {'name': 'Golem, Flesh', 'type': 'Construct', 'specials': '', 'description': 'Huge creature cobbled together from viarious body parts and brought to life.',
        'hp': '47', 'toTarget': 'normal', 'av': '0', 'STR': '7', 'DEX': '3', 'INT': '1', 'PRE': '2', 'statBlock': '7/3/1/2'},
    {'name': 'Homunculus', 'type': 'Construct', 'specials': 'Telepathy', 'description': 'A tiny hideous creature, humanlike but deformed. Created by magic. Fed on human blood. Communicates telepathically and obeys its creator.',
        'hp': '3', 'toTarget': 'Hard', 'av': '0', 'STR': '2', 'DEX': '5', 'INT': '3', 'PRE': '2', 'statBlock': '2/5/3/2'},
    {'name': 'Robot, Giant', 'type': 'Construct', 'specials': '', 'description': "Three story tall robot with laser eyes and smashing fists. All attacks 3d6 damage. Under someone's control.",
        'hp': '80', 'toTarget': 'Easy', 'av': '2', 'STR': '8', 'DEX': '4', 'INT': '0', 'PRE': '0', 'statBlock': '8/4/0/0'},
    {'name': 'Chupacabra', 'type': 'Cryptid', 'specials': '', 'description': 'Big blood-sucking canid with enormous teeth.',
        'hp': '20', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '4/5/0/3'},
    {'name': 'Sasquatch', 'type': 'Cryptid', 'specials': '', 'description': 'Bigfoot. Will throw rocks. Big rocks. Very mean, but usually only attacks upon provocation.',
        'hp': '25', 'toTarget': 'normal', 'av': '0', 'STR': '7', 'DEX': '4', 'INT': '1', 'PRE': '1', 'statBlock': '7/4/1/1'},
    {'name': 'Skunk Ape', 'type': 'Cryptid', 'specials': '', 'description': 'Smaller, quicker, very foul-smelling swamp sasquatch. Frenzied. Will attack instantly. Found in small groups.',
        'hp': '20', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '6', 'INT': '1', 'PRE': '1', 'statBlock': '5/6/1/1'},
    {'name': 'Swamp Demon', 'type': 'Cryptid', 'specials': '', 'description': 'Can emerge from or disappear into any still water, even a bathtub. Funky smelling. Claws.',
        'hp': '20', 'toTarget': 'Hard', 'av': '2', 'STR': '6', 'DEX': '3', 'INT': '2', 'PRE': '3', 'statBlock': '6/3/2/3'},
    {'name': 'Yeti', 'type': 'Cryptid', 'specials': '', 'description': 'The abominable snowman. Like sasquatch, but more aggressive and in cold places. Found in groups.',
        'hp': '26', 'toTarget': 'Easy', 'av': '', 'STR': '6', 'DEX': '5', 'INT': '1', 'PRE': '1', 'statBlock': '6/5/1/1'},
    {'name': 'Demon, Common', 'type': 'Demon', 'specials': 'Spell: Dopplegang', 'description': 'Lowest level demon. A foot soldier or messenger. 6’4” tall. Able to appear as a human.',
        'hp': '9', 'toTarget': 'Hard', 'av': '1', 'STR': '6', 'DEX': '4', 'INT': '3', 'PRE': '3', 'statBlock': '6/4/3/3'},
    {'name': 'Demon, Major', 'type': 'Demon', 'specials': 'Spells: Dopplegang, Fireball, Command, Fear (L2)', 'description': '20’ tall. Able to appear in human form without touching any target. Throws fireballs. All attacks do 2d6 damage.',
     'hp': '131', 'toTarget': 'Easy', 'av': '2', 'STR': '9', 'DEX': '5', 'INT': '5', 'PRE': '5', 'statBlock': '9/5/5/5'},
    {'name': 'Demon, Minor', 'type': 'Demon', 'specials': 'Spells: Dopplegang, Fireball', 'description': '12’ tall. Able to appear in human form without touching any target. Throws fireballs.',
        'hp': '42', 'toTarget': 'Easy', 'av': '1', 'STR': '6', 'DEX': '5', 'INT': '4', 'PRE': '4', 'statBlock': '6/5/4/4'},
    {'name': 'Demon, Thrall', 'type': 'Demon', 'specials': '', 'description': 'Possessed humans and favor seekers. ',
        'hp': '5', 'toTarget': 'Hard', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '2', 'PRE': '2', 'statBlock': '3/3/2/2'},
    {'name': 'Devil, Bone', 'type': 'Demon', 'specials': '', 'description': '', 'hp': '71',
        'toTarget': 'Easy', 'av': '2', 'STR': '6', 'DEX': '6', 'INT': '4', 'PRE': '4', 'statBlock': '6/6/4/4'},
    {'name': 'Devil, Horned', 'type': 'Demon', 'specials': '', 'description': '', 'hp': '89',
        'toTarget': 'Easy', 'av': '1', 'STR': '8', 'DEX': '6', 'INT': '4', 'PRE': '4', 'statBlock': '8/6/4/4'},
    {'name': 'Devil, Imp', 'type': 'Demon', 'specials': '', 'description': '', 'hp': '5',
        'toTarget': 'Hard', 'av': '0', 'STR': '2', 'DEX': '6', 'INT': '3', 'PRE': '3', 'statBlock': '2/6/3/3'},
    {'name': 'Devil, Pit Fiend', 'type': 'Demon', 'specials': '', 'description': '', 'hp': '150',
        'toTarget': 'Easy', 'av': '3', 'STR': '9', 'DEX': '5', 'INT': '2', 'PRE': '3', 'statBlock': '9/5/2/3'},
    {'name': 'Bugbear', 'type': 'Humanoid', 'specials': '', 'description': 'The biggest of the goblin species. Hairy and horrible. They love spiked clubs.',
        'hp': '14', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '5', 'INT': '2', 'PRE': '3', 'statBlock': '5/5/2/3'},
    {'name': 'Bugbear Chief', 'type': 'Humanoid', 'specials': '', 'description': 'Leads a group of 1-6 bugbears, and maybe even some goblins and hobgoblins.',
        'hp': '33', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '3', 'PRE': '3', 'statBlock': '6/5/3/3'},
    {'name': 'Coleopteran', 'type': 'Humanoid', 'specials': 'Natural Armor (AV 1)', 'description': 'Bug People. Spindly and slightly shorter than humans. Follow chemically issued orders from Queen.',
     'hp': '2', 'toTarget': 'normal', 'av': '1', 'STR': '3', 'DEX': '4', 'INT': '1', 'PRE': '3', 'statBlock': '3/4/1/3'},
    {'name': 'Coleopteran, Queen', 'type': 'Humanoid', 'specials': 'Natural Armor (AV 2)', 'description': '7’ tall. Clever. Commands 10 or more soldiers.',
     'hp': '20', 'toTarget': 'normal', 'av': '2', 'STR': '3', 'DEX': '4', 'INT': '6', 'PRE': '6', 'statBlock': '3/4/6/6'},
    {'name': 'Dwarf', 'type': 'Humanoid', 'specials': 'Darkvision', 'description': '3.5m tall, subterranian folk. Live in mountains. Love gold and gems. Exellent miners. Strong.',
        'hp': '6', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '3', 'INT': '3', 'PRE': '3', 'statBlock': '4/3/3/3'},
    {'name': 'Dwarf Leader', 'type': 'Humanoid', 'specials': 'Darkvision', 'description': 'Leads a settlment of dwarves.',
        'hp': '15', 'toTarget': 'normal', 'av': '3', 'STR': '5', 'DEX': '3', 'INT': '4', 'PRE': '5', 'statBlock': '5/3/4/5'},
    {'name': 'Dwarf, Fighter', 'type': 'Humanoid', 'specials': 'Darkvision', 'description': 'Dwarven foot soldier. Typically armed with war hammer or axe.',
        'hp': '10', 'toTarget': 'normal', 'av': '2', 'STR': '5', 'DEX': '3', 'INT': '3', 'PRE': '3', 'statBlock': '5/3/3/3'},
    {'name': 'Elf', 'type': 'Humanoid', 'specials': 'Darkvision', 'description': 'Slender, and slightly shorter than a human. Typically armed with a bow and long sword.',
        'hp': '5', 'toTarget': 'normal', 'av': '1', 'STR': '3', 'DEX': '4', 'INT': '3', 'PRE': '3', 'statBlock': '3/4/3/3'},
    {'name': 'Elf Leader', 'type': 'Humanoid', 'specials': 'Darkvision, Spells: Rose Binding, Cure Serious Wounds, Detect Foes, Charm',
        'description': 'Leads a band of elves. Uses magic.', 'hp': '13', 'toTarget': 'normal', 'av': '2', 'STR': '4', 'DEX': '4', 'INT': '4', 'PRE': '5', 'statBlock': '4/4/4/5'},
    {'name': 'Fishman', 'type': 'Humanoid', 'specials': 'Amphibious', 'description': 'Bipedal. Fish head. Amphibious. Very religious. Emotionally flat.',
        'hp': '7', 'toTarget': 'normal', 'av': '1', 'STR': '3', 'DEX': '3', 'INT': '3', 'PRE': '3', 'statBlock': '3/3/3/3'},
    {'name': 'Fishman Bishop', 'type': 'Humanoid', 'specials': 'Amphibious, Special Psychic Attack', 'description': 'Fishman religious zealot. Psychic focus on enemy causes drowning: lungs fill, water pours from mouth. Breaking focus ends effect.',
        'hp': '49', 'toTarget': 'normal', 'av': '1', 'STR': '4', 'DEX': '4', 'INT': '3', 'PRE': '5', 'statBlock': '4/4/3/5'},
    {'name': 'Gnoll', 'type': 'Humanoid', 'specials': '', 'description': 'Bipedal hyena/jackal creatures. Usually armed with swords & spears. Many wear armor. Guerrulous and greedy. ',
        'hp': '11', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '2', 'PRE': '2', 'statBlock': '5/4/2/2'},
    {'name': 'Gnoll Alpha', 'type': 'Humanoid', 'specials': '', 'description': 'A bigger, tougher Gnoll.',
        'hp': '25', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '2', 'PRE': '3', 'statBlock': '6/5/2/3'},
    {'name': 'Goblin', 'type': 'Humanoid', 'specials': 'Night Vision, Stealthy', 'description': '3.5m tall, smooth-skinned bipeds.They come in a variety of dark colors: blue, green, grey. Evil. Armed with bows and short swords. May wear light armor.',
        'hp': '4', 'toTarget': 'Hard', 'av': '0', 'STR': '3', 'DEX': '5', 'INT': '3', 'PRE': '2', 'statBlock': '3/5/3/2'},
    {'name': 'Goblin Boss', 'type': 'Humanoid', 'specials': 'Night Vision, Stealthy', 'description': 'Smarter goblin. Leads a group of 1d6+6 goblins.',
        'hp': '11', 'toTarget': 'Hard', 'av': '0', 'STR': '4', 'DEX': '5', 'INT': '3', 'PRE': '3', 'statBlock': '4/5/3/3'},
    {'name': 'Hobgoblin', 'type': 'Humanoid', 'specials': '', 'description': 'Cousins to the goblins, but hulking and hairy with big teeth. Typically fight with spears.',
        'hp': '8', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '3', 'PRE': '3', 'statBlock': '5/4/3/3'},
    {'name': 'Hobgoblin Captain', 'type': 'Humanoid', 'specials': '', 'description': 'Head of a group of 1d6+3 hobgoblins.',
        'hp': '20', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '5', 'INT': '4', 'PRE': '3', 'statBlock': '5/5/4/3'},
    {'name': 'Hobgoblin Warlord', 'type': 'Humanoid', 'specials': '', 'description': 'Leads an army of 1d6 Hobgoblin Captains, each with their own group of hobgoblin fighters.',
        'hp': '49', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '4', 'PRE': '4', 'statBlock': '6/5/4/4'},
    {'name': 'Lizardfolk', 'type': 'Humanoid', 'specials': 'Hold Breath, Chameleon Skin', 'description': 'Semi-aquatic bipedal lizard folk. Shallow emotions. Territorial and warlike. Spears & Swords.',
        'hp': '11', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '2', 'PRE': '3', 'statBlock': '5/4/2/3'},
    {'name': 'Lizardfolk King/Queen', 'type': 'Humanoid', 'specials': 'Hold Breath, Chameleon Skin, Spells: Fireball, Suffer',
        'description': 'Lizardfolk Leader.', 'hp': '39', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '4', 'INT': '3', 'PRE': '4', 'statBlock': '6/4/3/4'},
    {'name': 'Lizardfolk Shaman', 'type': 'Humanoid',
        'specials': 'Hold Breath, Chameleon Skin, Spells: Push, Pull, Cure Light Wounds, Arrow (L2)', 'description': 'Fighting clerics of the lizarfolk.', 'hp': '14', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '3', 'PRE': '3', 'statBlock': '5/4/3/3'},
    {'name': 'Merfolk', 'type': 'Humanoid', 'specials': 'Amphibious', 'description': 'Mermaids and Mermen. Fight with Tridents.',
        'hp': '6', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '5', 'INT': '3', 'PRE': '3', 'statBlock': '4/5/3/3'},
    {'name': 'Mole Man', 'type': 'Humanoid', 'specials': 'Burrower, Night Vision', 'description': 'Denizens of a huge, subterranean civilization. ',
        'hp': '3', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '3', 'INT': '3', 'PRE': '3', 'statBlock': '4/3/3/3'},
    {'name': 'Mole Man, Foreman', 'type': 'Humanoid', 'specials': 'Burrower, Night Vision', 'description': 'Oversees team of mole men diggers.',
        'hp': '9', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '3', 'PRE': '3', 'statBlock': '5/4/3/3'},
    {'name': 'MushroomMan Adult', 'type': 'Humanoid', 'specials': '', 'description': 'Bipedal fungi. They completely ignore other creatures unless confronted or attacked. Expansionist. Will silently come to claim territory by simly moving in.',
        'hp': '11', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '4', 'INT': '3', 'PRE': '3', 'statBlock': '4/4/3/3'},
    {'name': 'MushroomMan Sovereign', 'type': 'Humanoid', 'specials': '', 'description': 'A really big MushroomMan. All attacks 1d6+3 damage.',
        'hp': '30', 'toTarget': 'Easy', 'av': '0', 'STR': '4', 'DEX': '4', 'INT': '3', 'PRE': '5', 'statBlock': '4/4/3/5'},
    {'name': 'MushroomMan Sprout', 'type': 'Humanoid', 'specials': '',
        'description': 'Will begin to spring up where mushroomMen have moved in. Smaller. All attacks 1d6-2 damage (min. 1).', 'hp': '4', 'toTarget': 'Hard', 'av': '0', 'STR': '3', 'DEX': '4', 'INT': '2', 'PRE': '2', 'statBlock': '3/4/2/2'},
    {'name': 'Orc', 'type': 'Humanoid', 'specials': '', 'description': 'Piglike, muscular bipeds. Heavily armed and armored. Raiders and thieves.',
        'hp': '8', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '4', 'INT': '2', 'PRE': '3', 'statBlock': '6/4/2/3'},
    {'name': 'Orc War Chief', 'type': 'Humanoid', 'specials': '', 'description': 'Leads a group of 1d6+4 orcs.',
        'hp': '47', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '4', 'INT': '3', 'PRE': '4', 'statBlock': '6/4/3/4'},
    {'name': 'Troglodyte', 'type': 'Humanoid', 'specials': 'Chameleon Skin, Repulsive Spray', 'description': 'Underground cousins to Lizardfolk. Sworn enemies of Molemen. Very sneaky, and good at blending into the shadows. Very bad smelling.',
        'hp': '7', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '2', 'PRE': '2', 'statBlock': '5/4/2/2'},
    {'name': 'Apeman', 'type': 'Monster', 'specials': '', 'description': 'Travel in groups. Carnivorous and cannibalistic. Constant fight amongst themselves for control. Wear skins and fight with rocks, clubs, and stick spears.',
        'hp': '12', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '4', 'INT': '1', 'PRE': '3', 'statBlock': '6/4/1/3'},
    {'name': 'Basilisk', 'type': 'Monster', 'specials': 'Spell: Petrify', 'description': 'Giant Lizard, 2 times per day may cast Petrify by staring at target. Target is allowed Opposed Test of PRE to avoid petrification. Opponents suffer Disadvantage on relevant rolls while avioding the gaze of the basilisk.',
        'hp': '26', 'toTarget': 'normal', 'av': '2', 'STR': '6', 'DEX': '3', 'INT': '0', 'PRE': '2', 'statBlock': '6/3/0/2'},
    {'name': 'Black Pudding', 'type': 'Monster', 'specials': '', 'description': "Large, single-celled pudding. Digests anything it touches except stone. Any time a weapon hits a black pudding, if the Danger Die shows a 1, the weapon corrodes to nothing. Similarly, on successful attacks, the pudding will destroy target's armor on Danger Die 1. Immune to  slashing weapons, cold, and electricity, and acid.",
        'hp': '43', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '2', 'INT': '0', 'PRE': '1', 'statBlock': '6/2/0/1'},
    {'name': 'Centaur', 'type': 'Monster', 'specials': '', 'description': 'Human torso, horse body and legs. Will fight with swords, spears, or bows.',
        'hp': '23', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '3', 'PRE': '4', 'statBlock': '6/5/3/4'},
    {'name': 'Cyclops', 'type': 'Monster', 'specials': '', 'description': 'One-eyed giants. Unintelligent. Attack with clubs an thrown rocks for 2d6 damage. ',
        'hp': '69', 'toTarget': 'Easy', 'av': '1', 'STR': '8', 'DEX': '4', 'INT': '1', 'PRE': '2', 'statBlock': '8/4/1/2'},
    {'name': 'Doppelganger', 'type': 'Monster', 'specials': 'Shapeshift-People, Spell: Read Mind', 'description': 'Shapeshifter. Will assume the appearance of another person, including clothing, then try to kill them and take their place. Able to cast Read Mind spell.',
        'hp': '26', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '6', 'INT': '4', 'PRE': '5', 'statBlock': '4/6/4/5'},
    {'name': 'Dragon', 'type': 'Monster', 'specials': 'Breath Weapon', 'description': 'Classic Dragon. Has wings and can fly. Able to make two attacks per turn: bite, claw, or breath. Able to use breath attack 3 times per combat. All attacks do 2d6 damage. Color determines breath weapon type: Red - Fire, White - Frost, Green - Poisonous Gas, Black - Acid Cloud, Gold - Lightning. HP: lower value is for jeuvenile, higher is for adult. Adult dragons will know two of the following spells: Fear, Truth, Confuse, Cure Serious Wounds, Invisibility, Read Mind.',
        'hp': '75/128', 'toTarget': 'Easy', 'av': '2', 'STR': '9', 'DEX': '4', 'INT': '4', 'PRE': '5', 'statBlock': '9/4/4/5'},
    {'name': 'Dragon Turtle', 'type': 'Monster', 'specials': 'Breath Weapon: Steam', 'description': 'An aquatic dragon with a shell. As big as a ship. All attacks do 3d6 damage. Breathes steam jet.',
        'hp': '171', 'toTarget': 'Easy', 'av': '3', 'STR': '9', 'DEX': '4', 'INT': '3', 'PRE': '4', 'statBlock': '9/4/3/4'},
    {'name': 'Gargoyle', 'type': 'Monster', 'specials': '', 'description': 'Flying, horned monster. Claw and bite attacks. When still, they are indestinguishable from a statue. ',
        'hp': '26', 'toTarget': 'normal', 'av': '2', 'STR': '5', 'DEX': '4', 'INT': '2', 'PRE': '3', 'statBlock': '5/4/2/3'},
    {'name': 'Gelatinous Cube', 'type': 'Monster', 'specials': '', 'description': 'Slowly moving cube of clear jello, up to 3m tall. Scaveners that sweep dungeons clean, sweeping up everything, digesting organic material. Often cantain non-organic items, such as treasure, weapons, and armor. Hits do digestive damage to their target. On a successful hit with Danger Die showing 1 or 2, victim is also paralyzed for 1-3 turns. Immune to cold, electricity, sleap, paralyzation, and fear.',
        'hp': '42', 'toTarget': 'Easy', 'av': '0', 'STR': '5', 'DEX': '1', 'INT': '0', 'PRE': '1', 'statBlock': '5/1/0/1'},
    {'name': 'Genie, Djinni & Efreeti', 'type': 'Monster', 'specials': 'Flight, Shape Shift - sze, animal, people, Spell: Wisp, Special Ability: able to grant 3 wishes',
        'description': 'Enormously strong, shape shifting spirits. Efreeti are related to the djinni, but even more malevolent. A trapped djinni or efreeti, once released, must be a servant for 100 days or grant three wishes to fully gain its freedom.', 'hp': '80', 'toTarget': 'normal', 'av': '0', 'STR': '7', 'DEX': '5', 'INT': '5', 'PRE': '5', 'statBlock': '7/5/5/5'},
    {'name': 'Giant, High', 'type': 'Monster', 'specials': 'Spell: Earthquake', 'description': '10m tall. Dress in fine robes and jewelry. Highly cultured. Fight with huge sword or spear. May also stamp on target. All attacks do 3d6 damage. May cast Earthquake once per day.',
        'hp': '100', 'toTarget': 'Easy', 'av': '0', 'STR': '9', 'DEX': '4', 'INT': '5', 'PRE': '5', 'statBlock': '9/4/5/5'},
    {'name': 'Giant, Low', 'type': 'Monster', 'specials': '', 'description': '4m tall. Dresses in skins. Uses a huge club, or throws boulders. All attacks do 2d6 damage. Greedy and unintelligent.',
        'hp': '53', 'toTarget': 'Easy', 'av': '0', 'STR': '7', 'DEX': '3', 'INT': '1', 'PRE': '2', 'statBlock': '7/3/1/2'},
    {'name': 'Gnomillian', 'type': 'Monster', 'specials': 'Spell: Invisibility', 'description': 'Tough, mean little guys with pointed hats. 50cm tall. Fight with little swords. Lusty for treasure.',
        'hp': '8', 'toTarget': 'Hard', 'av': '0', 'STR': '5', 'DEX': '5', 'INT': '3', 'PRE': '3', 'statBlock': '5/5/3/3'},
    {'name': 'Gray Ooze', 'type': 'Monster', 'specials': '', 'description': 'Slime monster. Lookes like wet stone (DISADVANTAGE to detect). Touch will corrode metal armor and weapons. Damaged by fire and all weapon attacks.',
     'hp': '11', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '2', 'INT': '0', 'PRE': '1', 'statBlock': '4/2/0/1'},
    {'name': 'Griffon', 'type': 'Monster', 'specials': '', 'description': 'Head and front claws of an eagle, body of a lion. Can fly.',
        'hp': '30', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '6/5/0/3'},
    {'name': 'Hag, Night', 'type': 'Monster', 'specials': '', 'description': '', 'hp': '56',
        'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '5', 'PRE': '6', 'statBlock': '6/5/5/6'},
    {'name': 'Harpy', 'type': 'Monster', 'specials': '', 'description': 'Body of an eagle, torso and head of a human. Anyone hearing their song must pass a PRE check or be drawn passively to them to be eaten. Often found in groups of 2-4.',
        'hp': '19', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '5', 'INT': '2', 'PRE': '3', 'statBlock': '4/5/2/3'},
    {'name': 'Hell Hound', 'type': 'Monster', 'specials': '', 'description': 'Enormous midnight black dogs with red eyes, teeth and mouths. Might be sent by demons or other dark forces. May appear in packs. Relentless. Bite causes physical and electrical damage.',
        'hp': '23', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '4', 'INT': '2', 'PRE': '3', 'statBlock': '6/4/2/3'},
    {'name': 'Huay Chivo', 'type': 'Monster', 'specials': 'Shapeshift - Animal', 'description': 'A nagual who went fully feral. Half human, half goat, dog, or deer. Burning red eyes. Fast and frenzied. Will harass livestock and suck the blood of any animal or human.',
        'hp': '25', 'toTarget': 'Hard', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '6/5/0/3'},
    {'name': 'Hydra', 'type': 'Monster', 'specials': 'Breath Weapon: Fire', 'description': 'A dragon with 9 heads. All attacks do 2d6 damage. Every HP of damage the the hydra will kill one of the heads. Able to breathe fire 3 times per day.',
        'hp': '90', 'toTarget': 'Easy', 'av': '0', 'STR': '7', 'DEX': '4', 'INT': '0', 'PRE': '2', 'statBlock': '7/4/0/2'},
    {'name': 'Kobold', 'type': 'Monster', 'specials': '', 'description': '1m tall, scaly bipeds with horns. Fight with short swords or spears.',
        'hp': '3', 'toTarget': 'Hard', 'av': '0', 'STR': '3', 'DEX': '5', 'INT': '2', 'PRE': '2', 'statBlock': '3/5/2/2'},
    {'name': 'Kobold, Winged', 'type': 'Monster', 'specials': '', 'description': 'Like a regular Kobold, but able to fly.',
        'hp': '4', 'toTarget': 'Hard', 'av': '0', 'STR': '3', 'DEX': '6', 'INT': '2', 'PRE': '2', 'statBlock': '3/6/2/2'},
    {'name': 'Kraken', 'type': 'Monster', 'specials': '', 'description': 'Titanic tentacled sea monster. Able to grab ships. 2 attacks per turn. All attacks do 5d6 damage.',
        'hp': '236', 'toTarget': 'Easy', 'av': '0', 'STR': '10', 'DEX': '4', 'INT': '7', 'PRE': '6', 'statBlock': '10/4/7/6'},
    {'name': 'Lava Monster', 'type': 'Monster', 'specials': 'Spell: Fireball', 'description': '3m tall, made of lava. Attacks with big slap or fireballs. Immune to fire damage. Double damage from cold attacks. Submersion in water will turn them to stone.',
        'hp': '12', 'toTarget': 'normal', 'av': '2', 'STR': '6', 'DEX': '2', 'INT': '0', 'PRE': '1', 'statBlock': '6/2/0/1'},
    {'name': 'Lycanthrope, Beast Form', 'type': 'Monster', 'specials': 'Shapeshift - Animal, Regeneration', 'description': 'Werewolf, Werebear, Wererat, Weretiger. Transforms into half human/half animal. Regenerates 1d6 HP per turn, even after death, unless damaged by silver weapons, magic, or magical weapons. On successful attack, if danger die shows a 1, victim contracts lycanthropy. PCs who become lycanthropes must make a PRE check after every transformation.  Failure means they have no control over their actions and will attack anyone who it near.', 'hp': '35', 'toTarget': 'normal', 'av': '0', 'STR': '7', 'DEX': '4', 'INT': '3', 'PRE': '4', 'statBlock': '7/4/3/4'},
    {'name': 'Medusa', 'type': 'Monster', 'specials': 'Poisonous (Bite), Spell: Petrify', 'description': 'Humanoid with snakes for hair. Can attack with claws, bit or snakes. Anyone looking directly at a gorgon is immidiately struck with a Petrify spell. Action against gorgon with eyes averted is always at disadvantage.',
     'hp': '64', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '5', 'INT': '4', 'PRE': '4', 'statBlock': '4/5/4/4'},
    {'name': 'Minotaur', 'type': 'Monster', 'specials': '', 'description': "A huge guy with a bull's head. Armed with a battle axe 1d6+2 damage. Charge attack does 2d6 damage.",
        'hp': '38', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '4', 'INT': '1', 'PRE': '4', 'statBlock': '6/4/1/4'},
    {'name': 'Naga', 'type': 'Monster', 'specials': 'Poisonous (Bite), Constrictor', 'description': 'Huge snake with human torso. Armed with tridents or swords.',
     'hp': '40', 'toTarget': 'normal', 'av': 'normal', 'STR': '5', 'DEX': '5', 'INT': '3', 'PRE': '4', 'statBlock': '5/5/3/4'},
    {'name': 'Nagual', 'type': 'Monster', 'specials': 'Shapeshift - Animal, Spells: any 2 level 1', 'description': 'Brujo who can change form at night: jaguar, dog, owl, bat, wolf, or turkey. They drink human blood, cause disease, steal stuff, and eat children.',
        'hp': '20', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '4', 'INT': '3', 'PRE': '3', 'statBlock': '4/4/3/3'},
    {'name': 'Ochre Jelly', 'type': 'Monster', 'specials': '', 'description': 'A yellow, oozing jelly. Successful hit disolves the flesh of the target for one extra turn of damage. Only damaged by fire and cold attacks. Slashing and electrical attacks will divide the it into 1-6 smaller oozes, dividing remaining HP amongst them. ',
        'hp': '23', 'toTarget': 'Easy', 'av': '0', 'STR': '5', 'DEX': '2', 'INT': '0', 'PRE': '1', 'statBlock': '5/2/0/1'},
    {'name': 'Ogre', 'type': 'Monster', 'specials': '', 'description': 'Huge, ugly beast. Long teeth. May use a huge club. All attacks do 2d6 damage.',
        'hp': '30', 'toTarget': 'Easy', 'av': '0', 'STR': '7', 'DEX': '3', 'INT': '1', 'PRE': '2', 'statBlock': '7/3/1/2'},
    {'name': 'Oni', 'type': 'Monster', 'specials': 'Breath Weapon: Cold, Spells: Charm (L1), Sleep (L2)', 'description': 'Bigger, smarter ogres with blue or green skin. Oni use fancier weapons than regular ogres. All attacks do 2d6 damage. Oni have Breath Weapon: Cold, and can cast Charm and Sleep once per combat.',
     'hp': '55', 'toTarget': 'Easy', 'av': '0', 'STR': '7', 'DEX': '4', 'INT': '4', 'PRE': '4', 'statBlock': '7/4/4/4'},
    {'name': 'Pegasus', 'type': 'Monster', 'specials': 'Wings', 'description': 'A flying horse.', 'hp': '30',
        'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '3', 'PRE': '4', 'statBlock': '6/5/3/4'},
    {'name': 'Pixie', 'type': 'Monster', 'specials': 'Invisibility, Wings', 'description': 'Tiny little humanoid with wings. If they attack, they always surprise their target.',
        'hp': '1', 'toTarget': 'Hard', 'av': '0', 'STR': '1', 'DEX': '7', 'INT': '3', 'PRE': '4', 'statBlock': '1/7/3/4'},
    {'name': 'Pseudodragon', 'type': 'Monster', 'specials': 'Telepathy', 'description': 'Tiny dragon. No breath weapon. Tameable. Flies. Able to understand human speech, but cannot talk. Can communicate telepathically, but only simple concepts.',
        'hp': '4', 'toTarget': 'Hard', 'av': '0', 'STR': '2', 'DEX': '5', 'INT': '1', 'PRE': '3', 'statBlock': '2/5/1/3'},
    {'name': 'Quetzoquatl', 'type': 'Monster', 'specials': 'Wings, Constrictor', 'description': 'Flying, feathered snake. Constictor. Danger die 1 means bitten, held, and crushed for 2d6. Opposed STR check to break free.',
        'hp': '30', 'toTarget': 'Easy', 'av': '2', 'STR': '5', 'DEX': '4', 'INT': '2', 'PRE': '3', 'statBlock': '5/4/2/3'},
    {'name': 'Roc', 'type': 'Monster', 'specials': '', 'description': 'An enormous bird of prey. 30m wingspan. Two attacks per turn: claws and beak. All attacks to 3d6 damage. Danger Die 6 means the victim has been grasped in its beak or claws.',
        'hp': '124', 'toTarget': 'Easy', 'av': '0', 'STR': '10', 'DEX': '4', 'INT': '1', 'PRE': '3', 'statBlock': '10/4/1/3'},
    {'name': 'Satyr', 'type': 'Monster', 'specials': 'Calm, Spell: Charm', 'description': 'Half human, half goat. Armed with bow and short sword.',
        'hp': '16', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '6', 'INT': '4', 'PRE': '4', 'statBlock': '4/6/4/4'},
    {'name': 'Screaming Fungus', 'type': 'Monster', 'specials': '', 'description': '1m tall mushrooms found in dungeons and caverns. Light or movement within 10m will cause them to shriek loudly until they are destroyed. Roll 1d6 each turn they are shrieking. For each troll of 1-3, one random moster is attracted to investigate the noise.',
        'hp': '7', 'toTarget': 'normal', 'av': '0', 'STR': '1', 'DEX': '1', 'INT': '0', 'PRE': '0', 'statBlock': '1/1/0/0'},
    {'name': 'Skin Walker', 'type': 'Monster', 'specials': 'Shapeshift - People', 'description': 'Shapeshifter. Will assume the appearance of another person, including clothing, then try to kill them and take their place. When in their natural form, a skinwalker is a tall and skeletal, with leathery skin, long hair, and empty eyeholes.',
        'hp': '20', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '3', 'PRE': '4', 'statBlock': '3/3/3/4'},
    {'name': 'Sphinx', 'type': 'Monster', 'specials': '', 'description': 'Lion body, human torso. Often guarding places or things. Very smart. May negotiate, but will want money or treasure.',
        'hp': '68', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '6', 'PRE': '6', 'statBlock': '6/5/6/6'},
    {'name': 'Tree Man', 'type': 'Monster', 'specials': '', 'description': 'Anthropomorphized tree. Slow, but all attacks do 2d6 damage. Will try to pick up enemies and shake or throw them.',
        'hp': '30', 'toTarget': 'Easy', 'av': '2', 'STR': '7', 'DEX': '2', 'INT': '4', 'PRE': '4', 'statBlock': '7/2/4/4'},
    {'name': 'Troll', 'type': 'Monster', 'specials': 'Night Vision, Heightened Smell', 'description': 'Green, lurching, empty eyed monsters, Trolls hunt humans and others for food. Regenerate 3 HP per turn, except for damage caused by fire. Even after death, a trolls dismembered body parts will crawl towards one another and rejoin as it comes back to life. Corpse must be burned to stop regeneration.',
        'hp': '42', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '2', 'PRE': '2', 'statBlock': '6/5/2/2'},
    {'name': 'Unicorn', 'type': 'Monster', 'specials': 'Spell: Invisibility, Teleport (L10)', 'description': 'Very shy horse with one horn. May only be ridden by extrememly the virtuous.',
     'hp': '34', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '3', 'PRE': '5', 'statBlock': '6/5/3/5'},
    {'name': 'Wyvern', 'type': 'Monster', 'specials': 'Poisonous (Sting)', 'description': 'Smaller, winged dragon with a poisonous stinger on its tail. Claw, bite attacks 2d6 damage. Tail attack 1d6, Danger Die 1 or 2 means victim falls unconcious and takes 1d6 damage for 1-6 turns.',
     'hp': '55', 'toTarget': 'Easy', 'av': '0', 'STR': '7', 'DEX': '1', 'INT': '1', 'PRE': '3', 'statBlock': '7/1/1/3'},
    {'name': 'Alamadillo', 'type': 'Mutant', 'specials': 'Heightened Smell, Natural Armor', 'description': '2m tall bipedal armadillo people. Establish large, fully functional villages. A bit surly, but rational actors. They despise legmaphegs.',
        'hp': '10', 'toTarget': 'normal', 'av': '2', 'STR': '5', 'DEX': '3', 'INT': '3', 'PRE': '3', 'statBlock': '5/3/3/3'},
    {'name': 'Argy Bargle', 'type': 'Mutant', 'specials': '', 'description': 'Goose-sized parakeets that instictively love people. Sometimes kept as guard animals or pets.',
        'hp': '8', 'toTarget': 'normal', 'av': 'normal', 'STR': '2', 'DEX': '5', 'INT': '0', 'PRE': '4', 'statBlock': '2/5/0/4'},
    {'name': 'Barrel Barney', 'type': 'Mutant', 'specials': 'Darkvision', 'description': 'Turtle/morray eel hybrid. The size of a Volkswagon Beetle. Shell is camoflaged. Eel neck and head shoots out 3m to attack, then whips back in.',
        'hp': '30', 'toTarget': 'Easy', 'av': '3', 'STR': '6', 'DEX': '6', 'INT': '0', 'PRE': '3', 'statBlock': '6/6/0/3'},
    {'name': 'Boogin', 'type': 'Mutant', 'specials': 'Locking Jaw', 'description': "Irrational cannibalsitic humans with four arms. Boogins use primitive weapons, claws, or bite. On successful attack with Danger Die 1, the boogin has bitten the target and won't let go unless killed or given some very persuasive reason to. Bitten target takes 1d6 damage per turn until released.",
        'hp': '12', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '1', 'PRE': '3', 'statBlock': '5/4/1/3'},
    {'name': 'Cooper', 'type': 'Mutant', 'specials': 'Swift', 'description': 'Humanioid chickens. Culture is xenophobic and warlike. They use old and scavanged military gear. Not very intelligent. Very fast runners.',
        'hp': '6', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '1', 'PRE': '2', 'statBlock': '3/3/1/2'},
    {'name': 'Fleegon', 'type': 'Mutant', 'specials': 'Fear', 'description': '2m long dragonfly. Often in groups of 4. Will harry and nibble on anyone for 1d6-2 damage. If attacked, will use its Fear power first.',
        'hp': '12', 'toTarget': 'Hard', 'av': '1', 'STR': '3', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '3/5/0/3'},
    {'name': 'Green Venus', 'type': 'Mutant', 'specials': 'Poisonous Spray', 'description': 'Ambulatory venus flytrap. Successful attack with Danger Die 1 or 2 means poisonous spray paralyzes target 1-3 turns. Travel in herds.',
        'hp': '10', 'toTarget': 'Easy', 'av': 'normal', 'STR': '3', 'DEX': '2', 'INT': '0', 'PRE': '3', 'statBlock': '3/2/0/3'},
    {'name': 'HeeHoy', 'type': 'Mutant', 'specials': 'Blast: Sonic', 'description': "Huge, long-snouted hog with lots of teeth and long spindly legs. It's snort attack will stun anyone who fails an STR check for 1-3 turns. It may snort once every 4 turns. Often found in groups of 3.",
        'hp': '20', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '3', 'INT': '0', 'PRE': '3', 'statBlock': '4/3/0/3'},
    {'name': 'Impossum', 'type': 'Mutant', 'specials': 'Quicksand', 'description': 'Horse-sized Opposum. Can turn the ground around it to quicksand and submerge or swim away, at which time it is Hard to target. ',
        'hp': '30', 'toTarget': 'Easy', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '0', 'PRE': '3', 'statBlock': '5/4/0/3'},
    {'name': 'Legmapheg', 'type': 'Mutant', 'specials': 'Web Maker, Sticky, Poisonous (Bite)', 'description': "2m tall spider body with a human torso and arms. Don't be fooled. Does not think like a human. Lemaphegs live in colonies with mud homes and feed on humanoids. No one knows how they communicate.",
     'hp': '12', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '4', 'INT': '2', 'PRE': '3', 'statBlock': '4/4/2/3'},
    {'name': 'Longchook', 'type': 'Mutant', 'specials': '2 attacks per Turn, Mind Blast, Constrictor, Bioluminescence',
        'description': '2m tall day-glo orange ape with 4 tentacles. Glows in the dark, too.', 'hp': '50', 'toTarget': 'normal', 'av': '0', 'STR': '7', 'DEX': '4', 'INT': '0', 'PRE': '3', 'statBlock': '7/4/0/3'},
    {'name': 'Mister Boots', 'type': 'Mutant', 'specials': 'Exoskeleton', 'description': 'Cockroach that looks like a guy in a long coat and boots. Found in urban ruins and crowded settlements. Will stand quietly until approached, then unfold and attack with claws and mandibles. Wherever they are seen, there will be a nest of 6-36 somewhere nearby.',
        'hp': '8', 'toTarget': 'normal', 'av': '1', 'STR': '3', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '3/5/0/3'},
    {'name': 'Moss Hog', 'type': 'Mutant', 'specials': 'Immunities: Fire, Cold, Electricity, Acid, Radiation', 'description': '10m tall tardigrade. Eight clawed legs. Tubelike mouth full of long dagger teeth. Often found near giant moss. All attacks do 2d6 damage. Will eat anyting that moves. Only injured by slashing, bludgeoning, or piercing damage.',
        'hp': '70', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '3', 'INT': '0', 'PRE': '2', 'statBlock': '6/3/0/2'},
    {'name': 'Mutant, Big', 'type': 'Mutant', 'specials': '1 - 3 animal bases, 1-2 mutations.', 'description': '2 - 4m tall.',
        'hp': '30', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '0', 'PRE': '3', 'statBlock': '5/4/0/3'},
    {'name': 'Mutant, Enormous', 'type': 'Mutant', 'specials': '1 - 3 animal bases, 1-3 mutations.', 'description': '4 - 10m tall or more.',
        'hp': '90', 'toTarget': 'Easy', 'av': '0', 'STR': '8', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '8/5/0/3'},
    {'name': 'Mutant, Humanoid', 'type': 'Mutant', 'specials': '0-2 animal stocks, 1-3 mutations', 'description': 'A human who has been mutated. Add 1d6-4 animal stocks. Add 1-3 mutations.',
        'hp': '15', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '3', 'PRE': '3', 'statBlock': '3/3/3/3'},
    {'name': 'Mutant, Small', 'type': 'Mutant', 'specials': '1 - 3 animal bases, 1-2 mutations.', 'description': '10cm - 2m tall.',
        'hp': '10', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '0', 'PRE': '3', 'statBlock': '3/3/0/3'},
    {'name': 'Pellion', 'type': 'Mutant', 'specials': 'Night Vision, Heightened Senses, Leap', 'description': 'Pellions are a cross between a rat and a pomeranian dog, but the size of a German shepherd. Feral, they move in packs. They are sometimes domesticated as guard or companion animals.',
        'hp': '3', 'toTarget': 'Hard', 'av': '0', 'STR': '2', 'DEX': '4', 'INT': '0', 'PRE': '3', 'statBlock': '2/4/0/3'},
    {'name': 'Shockworm', 'type': 'Mutant', 'specials': 'Burrower, Breath Weapon: Lightning', 'description': 'Tapeworm/skink hybrid. 7m long with two front limbs and a pointed face covered with teeth. Bursts up through the ground to attack. Attracted to the vibrations and smell of humanoids.',
        'hp': '20', 'toTarget': 'normal', 'av': '', 'STR': '5', 'DEX': '3', 'INT': '0', 'PRE': '3', 'statBlock': '5/3/0/3'},
    {'name': 'Spittlebob', 'type': 'Mutant', 'specials': 'Sticky, Acid Spit', 'description': 'Cow-sized amoeba. Hides in/under things or drops from high places. Envelopes prey. Bladed and piercing weapons do half damage. Envoloped prey takes 1d6 damage per turn and must make an opposed STR check to escape. Danger Die 1 on attack means your weapon is stuck in the spittlebob.',
        'hp': '30', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '2', 'INT': '0', 'PRE': '2', 'statBlock': '6/2/0/2'},
    {'name': 'Spurgeon', 'type': 'Mutant', 'specials': 'Chameleon Skin', 'description': 'An aquatic cactus that swims like a fish. Shaped like a 5m long gar, with a long, toothy snout. Spurgeon blend into shallow water and pull waders under.',
        'hp': '20', 'toTarget': 'normal', 'av': '1', 'STR': '5', 'DEX': '3', 'INT': '0', 'PRE': '3', 'statBlock': '5/3/0/3'},
    {'name': 'Squatter Bulb', 'type': 'Mutant', 'specials': 'Prehensile Nose', 'description': 'A very large species of deep sea angler that has mutated to come out of the water. A vacuum bladder allows it to float and swim through the air. Will hide in foliage or rubble and pick up shiny artifacts with its prehensile nose lamp to dangle them as bait.',
        'hp': '25', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '3', 'INT': '0', 'PRE': '3', 'statBlock': '4/3/0/3'},
    {'name': 'Toddrels', 'type': 'Mutant', 'specials': 'Pick Pocket', 'description': '1m tall squirreloids. Travel in packs. Very descructive. Will swarm a group or camp and root through all their belongings, throwing things everywhere. 3 in 6 chance of  1-3 belongings missing after attack subsides, if any toddrels get away.',
        'hp': '4', 'toTarget': 'Hard', 'av': '0', 'STR': '2', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '2/5/0/3'},
    {'name': 'Human, Archmage', 'type': 'People', 'specials': 'Spells: Any 15', 'description': 'A powerful magic user, in any genre or period.',
        'hp': '50', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '5', 'INT': '6', 'PRE': '5', 'statBlock': '4/5/6/5'},
    {'name': 'Human, Assassin', 'type': 'People', 'specials': 'Stealthy, Deadeye', 'description': 'Specialized killer. Brought in by a boss when they need heavy lifting.',
        'hp': '39', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '6', 'INT': '4', 'PRE': '3', 'statBlock': '4/6/4/3'},
    {'name': 'Human, Civilian', 'type': 'People', 'specials': '', 'description': 'Normal Jane or Joe.', 'hp': '3',
        'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '3', 'PRE': '3', 'statBlock': '3/3/3/3'},
    {'name': 'Human, Crime Boss', 'type': 'People', 'specials': '', 'description': 'Generic Boss. Smart, tough, and in charge.',
        'hp': '30', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '5', 'INT': '5', 'PRE': '5', 'statBlock': '5/5/5/5'},
    {'name': 'Human, Cult Leader', 'type': 'People', 'specials': '', 'description': 'Evil, tough, smart, and charismatic.',
        'hp': '25', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '5', 'PRE': '5', 'statBlock': '3/3/5/5'},
    {'name': 'Human, Cultist', 'type': 'People', 'specials': '', 'description': 'Devoted to strange belief and/or charismatic leader.',
        'hp': '3', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '2', 'PRE': '3', 'statBlock': '3/3/2/3'},
    {'name': 'Human, Druid', 'type': 'People', 'specials': 'Shapeshift - Animal, Spells: 2 Nature Spells', 'description': '',
        'hp': '14', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '4', 'INT': '4', 'PRE': '4', 'statBlock': '4/4/4/4'},
    {'name': 'Human, Henchman', 'type': 'People', 'specials': '', 'description': 'Generic weak henchman. General use. Lowest of the low. Easily beaten or scared away. Adjust stats where appropriate.',
        'hp': '3', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '3', 'INT': '2', 'PRE': '2', 'statBlock': '4/3/2/2'},
    {'name': 'Human, Knight', 'type': 'People', 'specials': '2 attacks per Turn', 'description': 'Armed with heavy weapons, and armor. AV may be 1, 2, or 3.',
        'hp': '26', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '4', 'INT': '3', 'PRE': '4', 'statBlock': '6/4/3/4'},
    {'name': 'Human, Magic User', 'type': 'People', 'specials': 'Spells: Any 5', 'description': 'An person who has learned some basic magic. Could be from any genre or time period.',
        'hp': '20', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '5', 'PRE': '3', 'statBlock': '3/3/5/3'},
    {'name': 'Human, Spy', 'type': 'People', 'specials': 'Disquise, Stealthy', 'description': 'A basic espionage agent. Quick, tough, smart, and confident.',
        'hp': '14', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '5', 'INT': '4', 'PRE': '5', 'statBlock': '4/5/4/5'},
    {'name': 'Human, Thug', 'type': 'People', 'specials': '', 'description': "A baddie's captain. Stronger and tougher than they are smart.",
        'hp': '16', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '3', 'PRE': '3', 'statBlock': '5/4/3/3'},
    {'name': 'Human, Tough', 'type': 'People', 'specials': '', 'description': 'A soldier, guard, police officer, beat cop, bandit, etc. Basic fighting skills.',
        'hp': '6', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '4', 'INT': '3', 'PRE': '3', 'statBlock': '4/4/3/3'},
    {'name': 'Human, Veteran Soldier', 'type': 'People', 'specials': 'Deadeye', 'description': 'Seasoned veteran soldier, gang member, police detective,  etc. A good shot.',
        'hp': '29', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '5', 'INT': '3', 'PRE': '4', 'statBlock': '5/5/3/4'},
    {'name': 'Allosaurus', 'type': 'Prehistoric', 'specials': '', 'description': 'Smaller and quicker than the T-Rex.',
        'hp': '26', 'toTarget': 'Easy', 'av': '0', 'STR': '7', 'DEX': '5', 'INT': '0', 'PRE': '2', 'statBlock': '7/5/0/2'},
    {'name': 'Ankylosaurus', 'type': 'Prehistoric', 'specials': '', 'description': 'Hard shell armor, and a clubbed or spiked tail.',
        'hp': '34', 'toTarget': 'Easy', 'av': '3', 'STR': '7', 'DEX': '4', 'INT': '0', 'PRE': '2', 'statBlock': '7/4/0/2'},
    {'name': 'Axe Beak', 'type': 'Prehistoric', 'specials': '', 'description': 'Like an extra big ostrich with a square, sharp beak.',
        'hp': '10', 'toTarget': 'Easy', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '0', 'PRE': '2', 'statBlock': '5/4/0/2'},
    {'name': 'Caveman', 'type': 'Prehistoric', 'specials': 'Heightened Smell', 'description': 'Just like in the movies.',
        'hp': '8', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '3', 'INT': '1', 'PRE': '3', 'statBlock': '6/3/1/3'},
    {'name': 'Plesiosaurus', 'type': 'Prehistoric', 'specials': '', 'description': 'Aquatic, long neck, fins. Think Loch Ness Monster.',
        'hp': '34', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '0', 'PRE': '2', 'statBlock': '6/5/0/2'},
    {'name': 'Pterodactyl', 'type': 'Prehistoric', 'specials': '', 'description': 'Flying carnivore. Able to lift a up human sized victim.',
        'hp': '7', 'toTarget': 'normal', 'av': '0', 'STR': '7', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '7/5/0/3'},
    {'name': 'Saber-Toothed Tiger', 'type': 'Prehistoric', 'specials': '', 'description': 'Huge cat with 7" fangs.',
        'hp': '26', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '0', 'PRE': '3', 'statBlock': '6/5/0/3'},
    {'name': 'Triceratops', 'type': 'Prehistoric', 'specials': '', 'description': 'Herbivorous, but very dangerous. Three big horns and a frill shield.',
        'hp': '48', 'toTarget': 'Easy', 'av': '2', 'STR': '8', 'DEX': '3', 'INT': '0', 'PRE': '2', 'statBlock': '8/3/0/2'},
    {'name': 'Tyrannosaurus Rex', 'type': 'Prehistoric', 'specials': '', 'description': '4m – 6m tall. Huge teeth. Always hungry.',
        'hp': '68', 'toTarget': 'Easy', 'av': '0', 'STR': '9', 'DEX': '4', 'INT': '0', 'PRE': '3', 'statBlock': '9/4/0/3'},
    {'name': 'Wooly Mammoth', 'type': 'Prehistoric', 'specials': '', 'description': '3.5m tall elephant covered with hair.',
        'hp': '63', 'toTarget': 'Easy', 'av': '0', 'STR': '8', 'DEX': '3', 'INT': '0', 'PRE': '2', 'statBlock': '8/3/0/2'},
    {'name': 'Ghost', 'type': 'Undead', 'specials': 'Spell: Fear', 'description': 'Cannot be harmed by conventional means. Usually bound to a location.',
        'hp': '20', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '3', 'PRE': '4', 'statBlock': '3/3/3/4'},
    {'name': 'Ghoul', 'type': 'Undead', 'specials': '', 'description': 'Undead corpse. Quick, reactive, and frenzied. Hungers for human flesh. Heals 1 HP per turn.',
        'hp': '11', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '5', 'INT': '0', 'PRE': '2', 'statBlock': '5/5/0/2'},
    {'name': 'Lich', 'type': 'Undead', 'specials': '', 'description': 'An undead sorcerer, bent on power and destruction. Only injured by magic and magical weapons. Uses magic. May command a band, or even and army of undead creatures.',
        'hp': '65', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '6', 'INT': '6', 'PRE': '5', 'statBlock': '4/6/6/5'},
    {'name': 'Mummy Lord', 'type': 'Undead', 'specials': 'Command, Special: Summons Wasp Swarms', 'description': 'Wants to assimilate organs to become living. Suffers half damage from blades. Has Command Skill. Can Summon a swarm of wasps.',
        'hp': '50', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '4', 'INT': '3', 'PRE': '5', 'statBlock': '6/4/3/5'},
    {'name': 'Mummy Noble', 'type': 'Undead', 'specials': 'Command ', 'description': 'Wants to assimilate organs to become living. Suffers half damage from blades. Has Command Skill.',
        'hp': '35', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '3', 'INT': '3', 'PRE': '4', 'statBlock': '6/3/3/4'},
    {'name': 'Mummy, Common', 'type': 'Undead', 'specials': '', 'description': 'Just a mummy. Suffers half damage from blades. ',
        'hp': '20', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '3', 'INT': '2', 'PRE': '3', 'statBlock': '6/3/2/3'},
    {'name': 'Revenant', 'type': 'Undead', 'specials': 'Regeneration, Spells: Fear', 'description': 'An undead body, but intelligent and driven by revenge and hatred. Will dress and act as a normal person, but close interaction will betray an eerie wrongness. Regenerates 3 HP per turn. ',
        'hp': '68', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '5', 'INT': '4', 'PRE': '5', 'statBlock': '6/5/4/5'},
    {'name': 'Skeleton', 'type': 'Undead', 'specials': '', 'description': 'Typically armed with swords or bows. Blade weapons and bullets do half damage against a skeleton.',
        'hp': '7', 'toTarget': 'normal', 'av': '0', 'STR': '4', 'DEX': '5', 'INT': '0', 'PRE': '2', 'statBlock': '4/5/0/2'},
    {'name': 'Vampire', 'type': 'Undead', 'specials': 'Command, Hypnotic Suggestion, Spells: Wisp, Animal form: wolf, bat', 'description': 'Any vampire stuff you can think of applies. Can change into wolf or bat. Has Command skill. Will drink the blood of victims, if able. Prolonged use of victim for blood without killing them makes them become a vampire. Only damaged by silver weapons or magic. Is destroyed by sunlight. Hates garlic and holy symbols. No reflection in mirrors. Have to sleep in a coffin. Regenerate 3 HP per turn. If reduced to 0 HP, will turn into a cloud of mist and return to coffin. Must have stake driven through heart to be really dead.', 'hp': '72', 'toTarget': 'normal', 'av': '0', 'STR': '6', 'DEX': '6', 'INT': '5', 'PRE': '5', 'statBlock': '6/6/5/5'},
    {'name': 'Vampire Thrall', 'type': 'Undead', 'specials': 'Sticky', 'description': 'Under the control of a vampire. Hopes to become a vampire. Can crawl on walls and ceilings. ',
        'hp': '41', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '3', 'PRE': '2', 'statBlock': '3/3/3/2'},
    {'name': 'Wight', 'type': 'Undead', 'specials': '', 'description': 'Undead corpse half in the another plane, half in this world. Only harmed by silver weapons or magic. Hates the living. On being touched by a wight, the target must make a successful STR check or lose 1 level and associated HP. Being reduced to level 0 causes target to enter a coma and become a wight in 1d6 days. Uncurse spell will return them to Level 1.',
        'hp': '23', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '5', 'INT': '3', 'PRE': '4', 'statBlock': '5/5/3/4'},
    {'name': 'Wraith', 'type': 'Undead', 'specials': '', 'description': 'Incorporeal evil. Only damaged by silver weapons, magic weapons, or magic. Successful attack and danger die 1 or 2 causes victim’s STR to drop to 1 for 24 hours.',
        'hp': '34', 'toTarget': 'normal', 'av': '0', 'STR': '2', 'DEX': '6', 'INT': '4', 'PRE': '4', 'statBlock': '2/6/4/4'},
    {'name': 'Zombie', 'type': 'Undead', 'specials': '', 'description': 'Slow and mindless. Immune to injury except for the brain. Easy to hit, hard to injure.',
        'hp': '1', 'toTarget': 'Hard', 'av': '3', 'STR': '5', 'DEX': '2', 'INT': '0', 'PRE': '1', 'statBlock': '5/2/0/1'},
    {'name': 'Ether Gaunt', 'type': 'Xenoplanar', 'specials': 'Psychic Vampire, Teleport', 'description': 'Tall, faceless, black ether-devils with long tails. They come when you’re sleeping.',
        'hp': '15', 'toTarget': 'normal', 'av': '0', 'STR': '3', 'DEX': '3', 'INT': '5', 'PRE': '3', 'statBlock': '3/3/5/3'},
    {'name': 'Horror, Major', 'type': 'Xenoplanar', 'specials': '3 Random Specials, 3 Spells', 'description': 'Huge. 15m tall. Always angry. Always hungry. May command 2-12 minions. All attacks do 3d6 damage. Has 3 specials, and knows at least 3 spells.',
        'hp': '150', 'toTarget': 'Easy', 'av': '0', 'STR': '9', 'DEX': '4', 'INT': '6', 'PRE': '6', 'statBlock': '9/4/6/6'},
    {'name': 'Horror, Minion', 'type': 'Xenoplanar', 'specials': '1 Random Special', 'description': '1 - 2m tall. Xenoplanar peon. Has 1 special. Fast and hard to hit.',
        'hp': '10', 'toTarget': 'Hard', 'av': '0', 'STR': '3', 'DEX': '6', 'INT': '2', 'PRE': '3', 'statBlock': '3/6/2/3'},
    {'name': 'Horror, Minor', 'type': 'Xenoplanar', 'specials': '2 Random Specials, 1 Spell', 'description': '5m tall. Usually pretty worked up. All attacks do 2d6 damage. Has 2 specials and knows at least 1 spell.',
        'hp': '75', 'toTarget': 'Easy', 'av': '0', 'STR': '6', 'DEX': '4', 'INT': '4', 'PRE': '4', 'statBlock': '6/4/4/4'},
    {'name': 'Horror, Thrall', 'type': 'Xenoplanar', 'specials': 'none', 'description': 'A human who has sworn allegiance to a xenoplanar horror and has undergone transformation. Stronger, weirder. May know 2 spells. Regenerates 3 HP per turn. Looks normal, but may be hiding 1-3 surreal bits from list.',
        'hp': '12', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '3', 'INT': '3', 'PRE': '3', 'statBlock': '5/3/3/3'},
    {'name': 'Moon-Beast', 'type': 'Xenoplanar', 'specials': 'Sticky Tongue', 'description': 'Large, putrid toad creatures with trans-dimensional ships. Slave traders. Love rubies.',
        'hp': '10', 'toTarget': 'normal', 'av': '0', 'STR': '5', 'DEX': '4', 'INT': '3', 'PRE': '1', 'statBlock': '5/4/3/1'}
]
